export const masterSkills = {
  Alchemy: {show:true, rank: 0},
  Arcana: {show:true, rank: 0},
  Astrocartography: {show:true, rank: 0},
  Athletics: {show:true, rank: 0},
  Brawl: {show:true, rank: 0},
  Charm: {show:true, rank: 0},
  Coercion: {show:true, rank: 0},
  Computers: {show:true, rank: 0},
  Cool: {show:true, rank: 0},
  Coordination: {show:true, rank: 0},
  Deception: {show:true, rank: 0},
  Discipline: {show:true, rank: 0},
  Divine: {show:true, rank: 0},
  Driving: {show:true, rank: 0},
  Gunnery: {show:true, rank: 0},
  Knowledge: {show:true, rank: 0},
  Leadership: {show:true, rank: 0},
  Mechanics: {show:true, rank: 0},
  Medicine: {show:true, rank: 0},
  Melee: {show:true, rank: 0},
  MeleeHeavy: {show:true, rank: 0},
  MeleeLight: {show:true, rank: 0},
  Negotiation: {show:true, rank: 0},
  Operating: {show:true, rank: 0},
  Perception: {show:true, rank: 0},
  Piloting: {show:true, rank: 0},
  Primal: {show:true, rank: 0},
  Ranged: {show:true, rank: 0},
  RangedHeavy: {show:true, rank: 0},
  RangedLight: {show:true, rank: 0},
  Resilience: {show:true, rank: 0},
  Riding: {show:true, rank: 0},
  Skullduggery: {show:true, rank: 0},
  Stealth: {show:true, rank: 0},
  Streetwise: {show:true, rank: 0},
  Survival: {show:true, rank: 0},
  Vigilance: {show:true, rank: 0}
}

export const masterTalents = {
  1:{1:''}
}

export const blankSkills = {
  Alchemy: {},
  Arcana: {},
  Astrocartography: {},
  Athletics: {},
  Brawl: {},
  Charm: {},
  Coercion: {},
  Computers: {},
  Cool: {},
  Coordination: {},
  Deception: {},
  Discipline: {},
  Divine: {},
  Driving: {},
  Gunnery: {},
  Knowledge: {},
  Leadership: {},
  Mechanics: {},
  Medicine: {},
  Melee: {},
  MeleeHeavy: {},
  MeleeLight: {},
  Negotiation: {},
  Operating: {},
  Perception: {},
  Piloting: {},
  Primal: {},
  Ranged: {},
  RangedHeavy: {},
  RangedLight: {},
  Resilience: {},
  Riding: {},
  Skullduggery: {},
  Stealth: {},
  Streetwise: {},
  Survival: {},
  Vigilance: {}
}
