export const dataTypes = [
    'archetype',
    'archetypeSpecialSkills',
    'career',
    'careerSkills',
    'masterMotivations',
    'masterSkills',
    'masterTalents',
    'creationCharacteristics',
    'talentModifiers',
    'currentWound',
    'currentStrain',
    'earnedXP',
    'critical',
    'description',
];